export type Province =
  | 'Abra'
  | 'Agusan Del Norte'
  | 'Agusan Del Sur'
  | 'Aklan'
  | 'Albay'
  | 'Antique'
  | 'Aurora'
  | 'Bataan'
  | 'Batangas'
  | 'Benguet'
  | 'Biliran'
  | 'Bohol'
  | 'Bukidnon'
  | 'Bulacan'
  | 'Cagayan'
  | 'Camarines Norte'
  | 'Camarines Sur'
  | 'Camiguin'
  | 'Capiz'
  | 'Catanduanes'
  | 'Cavite'
  | 'Cebu'
  | 'Cotabato'
  | 'Davao Del Norte'
  | 'Davao Del Sur'
  | 'Davao de Oro'
  | 'Davao Oriental'
  | 'Eastern Samar'
  | 'Guimaras'
  | 'Ifugao'
  | 'Ilocos Norte'
  | 'Ilocos Sur'
  | 'Iloilo'
  | 'Isabela'
  | 'Kalinga'
  | 'Laguna'
  | 'Lanao Del Norte'
  | 'La Union'
  | 'Lazada Office'
  | 'Leyte'
  | 'Marawi'
  | 'Marinduque'
  | 'Metro Manila'
  | 'Misamis Occidental'
  | 'Misamis Oriental'
  | 'Mountain Province'
  | 'Negros Occidental'
  | 'Negros Oriental'
  | 'North Cotabato'
  | 'Northern Samar'
  | 'Nueva Ecija'
  | 'Nueva Vizcaya'
  | 'Occidental Mindoro'
  | 'Oriental Mindoro'
  | 'Palawan'
  | 'Pampanga'
  | 'Pangasinan'
  | 'Quezon'
  | 'Quirino'
  | 'Rizal'
  | 'Romblon'
  | 'Sarangani'
  | 'Siquijor'
  | 'Sorsogon'
  | 'South Cotabato'
  | 'Southern Leyte'
  | 'Sultan Kudarat'
  | 'Surigao Del Norte'
  | 'Surigao Del Sur'
  | 'Tarlac'
  | 'Western Samar'
  | 'Zambales'
  | 'Zamboanga Del Norte'
  | 'Zamboanga Del Sur'
  | 'Zamboanga Sibugay';
export type City = string;

export const regions: Record<Province, City[]> = {
  Abra: [
    'Bangued',
    'Bucay',
    'Bucloc',
    'Daguioman',
    'Danglas',
    'Dolores',
    'Lacub',
    'Lagangilang',
    'Lagayan',
    'La Paz',
    'Licuan-Baay',
    'Luba',
    'Malibcong',
    'Manabo',
    'Penarrubia',
    'Pidigan',
    'Pilar',
    'Sallapadan',
    'San Isidro',
    'San Juan',
    'San Quintin',
    'Tayum',
    'Tineg',
    'Tubo',
    'Villaviciosa',
  ],
  'Agusan Del Norte': [
    'Buenavista',
    'Butuan',
    'Cabadbaran',
    'Carmen',
    'Jabonga',
    'Kitcharao',
    'Las Nieves',
    'Magallanes',
    'Nasipit',
    'Remedios T. Romualdez',
    'Santiago',
    'Tubay',
  ],
  'Agusan Del Sur': [
    'Bayugan',
    'Bunawan',
    'Esperanza',
    'La Paz',
    'Loreto',
    'Prosperidad',
    'Rosario',
    'San Francisco',
    'San Luis',
    'Santa Josefa',
    'Sibagat',
    'Talacogon',
    'Trento',
    'Veruela',
  ],
  Aklan: [
    'Altavas',
    'Balete',
    'Banga',
    'Batan',
    'Buruanga',
    'Ibajay',
    'Kalibo',
    'Lezo',
    'Libacao',
    'Madalag',
    'Makato',
    'Malay',
    'Malinao',
    'Nabas',
    'New Washington',
    'Numancia',
    'Tangalan',
  ],
  Albay: [
    'Bacacay',
    'Camalig',
    'Daraga',
    'Guinobatan',
    'Jovellar',
    'Legazpi',
    'Libon',
    'Ligao',
    'Malilipot',
    'Malinao',
    'Manito',
    'Oas',
    'Pio Duran',
    'Polangui',
    'Rapu-Rapu',
    'Santo Domingo',
    'Tabaco',
    'Tiwi',
  ],
  Antique: [
    'Anini-Y',
    'Barbaza',
    'Belison',
    'Bugasong',
    'Caluya',
    'Culasi',
    'Hamtic',
    'Laua-An',
    'Libertad',
    'Pandan',
    'Patnongon',
    'San Jose',
    'San Remigio',
    'Sebaste',
    'Sibalom',
    'Tibiao',
    'Tobias Fornier',
    'Valderrama',
  ],
  Aurora: ['Baler', 'Casiguran', 'Dilasag', 'Dinalungan', 'Dingalan', 'Dipaculao', 'Maria Aurora', 'San Luis'],
  Bataan: [
    'Abucay',
    'Bagac',
    'Balanga',
    'Dinalupihan',
    'Hermosa',
    'Limay',
    'Mariveles',
    'Morong',
    'Orani',
    'Orion',
    'Pilar',
    'Samal',
  ],
  Batangas: [
    'Agoncillo',
    'Alitagtag',
    'Balayan',
    'Balete',
    'Batangas',
    'Bauan',
    'Calaca',
    'Calatagan',
    'Cuenca',
    'Ibaan',
    'Laurel',
    'Lemery',
    'Lian',
    'Lipa',
    'Lobo',
    'Mabini',
    'Malvar',
    'Mataasnakahoy',
    'Nasugbu',
    'Padre Garcia',
    'Rosario',
    'San Jose',
    'San Juan',
    'San Luis',
    'San Nicolas',
    'San Pascual',
    'Santa Teresita',
    'Santo Tomas',
    'Taal',
    'Talisay',
    'Tanauan',
    'Taysan',
    'Tingloy',
    'Tuy',
  ],
  Benguet: [
    'Atok',
    'Baguio',
    'Bakun',
    'Bokod',
    'Buguias',
    'Itogon',
    'Kabayan',
    'Kapangan',
    'Kibungan',
    'La Trinidad',
    'Mankayan',
    'Sablan',
    'Tuba',
    'Tublay',
  ],
  Biliran: ['Almeria', 'Biliran', 'Cabucgayan', 'Caibiran', 'Culaba', 'Kawayan', 'Maripipi', 'Naval'],
  Bohol: [
    'Alburquerque',
    'Alicia',
    'Anda',
    'Antequera',
    'Baclayon',
    'Balilihan',
    'Batuan',
    'Bien Unido',
    'Bilar',
    'Buenavista',
    'Calape',
    'Candijay',
    'Carmen',
    'Catigbian',
    'Clarin',
    'Corella',
    'Cortes',
    'Dagohoy',
    'Bohol',
    'Dauis',
    'Dimiao',
    'Duero',
    'Garcia Hernandez',
    'Getafe',
    'Guindulman',
    'Inabanga',
    'Jagna',
    'Lila',
    'Loay',
    'Loboc',
    'Loon',
    'Mabini',
    'Maribojoc',
    'Panglao',
    'Pilar',
    'Pres. Carlos P. Garcia (Pitogo)',
    'Sagbayan (Borja)',
    'San Isidro',
    'San Miguel',
    'Sevilla',
    'Sierra Bullones',
    'Sikatuna',
    'Tagbilaran',
    'Talibon',
    'Trinidad',
    'Tubigon',
    'Ubay',
    'Valencia',
  ],
  Bukidnon: [
    'Baungon',
    'Cabanglasan',
    'Damulog',
    'Dangcagan',
    'Don Carlos',
    'Impasug-Ong',
    'Kadingilan',
    'Kalilangan',
    'Kibawe',
    'Kitaotao',
    'Lantapan',
    'Libona',
    'Malaybalay',
    'Malitbog',
    'Manolo Fortich',
    'Maramag',
    'Pangantucan',
    'Quezon',
    'San Fernando',
    'Sumilao',
    'Talakag',
    'Valencia',
  ],
  Bulacan: [
    'Angat',
    'Balagtas (Bigaa)',
    'Baliuag',
    'Bocaue',
    'Bulacan',
    'Bustos',
    'Calumpit',
    'Dona Remedios Trinidad',
    'Guiguinto',
    'Hagonoy',
    'Malolos',
    'Marilao',
    'Meycauayan',
    'Norzagaray',
    'Obando',
    'Pandi',
    'Paombong',
    'Plaridel',
    'Pulilan',
    'San Ildefonso',
    'San Jose Del Monte',
    'San Miguel',
    'San Rafael',
    'Santa Maria',
  ],
  Cagayan: [
    'Abulug',
    'Alcala',
    'Allacapan',
    'Amulung',
    'Aparri',
    'Baggao',
    'Ballesteros',
    'Buguey',
    'Calayan',
    'Camalaniugan',
    'Claveria',
    'Enrile',
    'Gattaran',
    'Gonzaga',
    'Iguig',
    'Lal-Lo',
    'Lasam',
    'Pamplona',
    'Penablanca',
    'Piat',
    'Rizal',
    'Sanchez-Mira',
    'Santa Ana',
    'Santa Praxedes',
    'Santa Teresita',
    'Santo Nino (Faire)',
    'Solana',
    'Tuao',
    'Tuguegarao',
  ],
  'Camarines Norte': [
    'Basud',
    'Capalonga',
    'Daet',
    'Jose Panganiban',
    'Labo',
    'Mercedes',
    'Paracale',
    'San Lorenzo Ruiz',
    'Santa Elena',
    'San Vicente',
    'Talisay',
    'Vinzons',
  ],
  'Camarines Sur': [
    'Baao',
    'Balatan',
    'Bato',
    'Bombon',
    'Buhi',
    'Bula',
    'Cabusao',
    'Calabanga',
    'Camaligan',
    'Canaman',
    'Caramoan',
    'Del Gallego',
    'Gainza',
    'Garchitorena',
    'Goa',
    'Iriga',
    'Lagonoy',
    'Libmanan',
    'Lupi',
    'Magarao',
    'Milaor',
    'Minalabac',
    'Nabua',
    'Naga',
    'Ocampo',
    'Pamplona',
    'Pasacao',
    'Pili',
    'Presentacion',
    'Ragay',
    'Sagnay',
    'San Fernando',
    'San Jose',
    'Sipocot',
    'Siruma',
    'Tigaon',
    'Tinambac',
  ],
  Camiguin: ['Catarman', 'Guinsiliban', 'Mahinog', 'Mambajao', 'Sagay'],
  Capiz: [
    'Cuartero',
    'Dao',
    'Dumalag',
    'Dumarao',
    'Ivisan',
    'Jamindan',
    'Ma-Ayon',
    'Mambusao',
    'Panay',
    'Panitan',
    'Pilar',
    'Pontevedra',
    'President Roxas',
    'Roxas',
    'Sapi-An',
    'Sigma',
    'Tapaz',
  ],
  Catanduanes: [
    'Bagamanoc',
    'Baras',
    'Bato',
    'Caramoran',
    'Gigmoto',
    'Pandan',
    'Panganiban',
    'San Andres',
    'San Miguel',
    'Viga',
    'Virac',
  ],
  Cavite: [
    'Alfonso',
    'Amadeo',
    'Bacoor',
    'Carmona',
    'Cavite',
    'Dasmarinas',
    'Gen. Mariano Alvarez',
    'General Emilio Aguinaldo',
    'General Trias',
    'Imus',
    'Indang',
    'Kawit',
    'Magallanes',
    'Maragondon',
    'Mendez-Nunez',
    'Naic',
    'Noveleta',
    'Rosario',
    'Silang',
    'Tagaytay',
    'Tanza',
    'Ternate',
    'Trece Martires',
  ],
  Cebu: [
    'Alcantara',
    'Alcoy',
    'Alegria',
    'Aloguinsan',
    'Argao',
    'Asturias',
    'Badian',
    'Balamban',
    'Bantayan',
    'Barili',
    'Bogo',
    'Boljoon',
    'Borbon',
    'Carcar',
    'Carmen',
    'Catmon',
    'Cebu',
    'Compostela',
    'Consolacion',
    'Cordoba',
    'Daanbantayan',
    'Dalaguete',
    'Danao',
    'Dumanjug',
    'Ginatilan',
    'Lapu-Lapu',
    'Liloan',
    'Madridejos',
    'Malabuyoc',
    'Mandaue',
    'Medellin',
    'Minglanilla',
    'Moalboal',
    'Naga',
    'Oslob',
    'Pilar',
    'Pinamungahan',
    'Poro',
    'Ronda',
    'Samboan',
    'San Fernando',
    'San Francisco',
    'San Remigio',
    'Santa Fe',
    'Santander',
    'Sibonga',
    'Sogod',
    'Tabogon',
    'Tabuelan',
    'Talisay',
    'Toledo',
    'Tuburan',
    'Tudela',
  ],
  Cotabato: ['Cotabato'],
  'Davao Del Norte': [
    'Asuncion',
    'Braulio E. Dujali',
    'Carmen',
    'Island Garden Of Samal',
    'Kapalong',
    'New Corella',
    'Panabo',
    'San Isidro',
    'Santo Tomas',
    'Tagum',
    'Talaingod',
  ],
  'Davao Del Sur': [
    'Bansalan',
    'Davao',
    'Digos',
    'Don Marcelino',
    'Hagonoy',
    'Jose Abad Santos',
    'Kiblawan',
    'Magsaysay',
    'Malalag',
    'Malita',
    'Matanao',
    'Padada',
    'Santa Cruz',
    'Santa Maria',
    'Sarangani',
    'Sulop',
  ],
  'Davao de Oro': [
    'Compostela',
    'Laak (San Vicente)',
    'Mabini (Dona Alicia)',
    'Maco',
    'Maragusan (San Mariano)',
    'Mawab',
    'Monkayo',
    'Montevista',
    'Nabunturan',
    'New Bataan',
    'Pantukan',
  ],
  'Davao Oriental': [
    'Baganga',
    'Banaybanay',
    'Boston',
    'Caraga',
    'Cateel',
    'Governor Generoso',
    'Lupon',
    'Manay',
    'Mati',
    'San Isidro',
    'Tarragona',
  ],
  'Eastern Samar': [
    'Arteche',
    'Balangiga',
    'Balangkayan',
    'Borongan',
    'Can-Avid',
    'Dolores',
    'General Macarthur',
    'Giporlos',
    'Guiuan',
    'Hernani',
    'Jipapad',
    'Lawaan',
    'Llorente',
    'Maslog',
    'Maydolong',
    'Mercedes',
    'Oras',
    'Quinapondan',
    'Salcedo',
    'San Julian',
    'San Policarpo',
    'Sulat',
    'Taft',
  ],
  Guimaras: ['Buenavista', 'Jordan', 'Nueva Valencia', 'San Lorenzo', 'Sibunag'],
  Ifugao: [
    'Aguinaldo',
    'Alfonso Lista',
    'Asipulo',
    'Banaue',
    'Hingyon',
    'Hungduan',
    'Kiangan',
    'Lagawe',
    'Lamut',
    'Mayoyao',
    'Tinoc',
  ],
  'Ilocos Norte': [
    'Adams',
    'Bacarra',
    'Badoc',
    'Bangui',
    'Banna',
    'Batac',
    'Burgos',
    'Carasi',
    'Currimao',
    'Dingras',
    'Dumalneg',
    'Laoag',
    'Marcos',
    'Nueva Era',
    'Pagudpud',
    'Paoay',
    'Pasuquin',
    'Piddig',
    'Pinili',
    'San Nicolas',
    'Sarrat',
    'Solsona',
    'Vintar',
  ],
  'Ilocos Sur': [
    'Alilem',
    'Banayoyo',
    'Bantay',
    'Burgos',
    'Cabugao',
    'Candon',
    'Caoayan',
    'Cervantes',
    'Galimuyod',
    'Gregorio Del Pilar (Concepcion)',
    'Lidlidda',
    'Magsingal',
    'Nagbukel',
    'Narvacan',
    'Quirino (Angkaki)',
    'Salcedo (Baugen)',
    'San Emilio',
    'San Esteban',
    'San Ildefonso',
    'San Juan (Lapog)',
    'Santa',
    'Santa Catalina',
    'Santa Cruz',
    'Santa Lucia',
    'Santa Maria',
    'Santiago',
    'Santo Domingo',
    'San Vicente',
    'Sigay',
    'Sinait',
    'Sugpon',
    'Suyo',
    'Tagudin',
    'Vigan',
  ],
  Iloilo: [
    'Ajuy',
    'Alimodian',
    'Anilao',
    'Badiangan',
    'Balasan',
    'Banate',
    'Barotac Nuevo',
    'Barotac Viejo',
    'Batad',
    'Bingawan',
    'Cabatuan',
    'Calinog',
    'Carles',
    'Concepcion',
    'Dingle',
    'Duenas',
    'Dumangas',
    'Estancia',
    'Guimbal',
    'Igbaras',
    'Iloilo',
    'Janiuay',
    'Lambunao',
    'Leganes',
    'Lemery',
    'Leon',
    'Maasin',
    'Miagao',
    'Mina',
    'New Lucena',
    'Oton',
    'Passi',
    'Pavia',
    'Pototan',
    'San Dionisio',
    'San Enrique',
    'San Joaquin',
    'San Miguel',
    'San Rafael',
    'Santa Barbara',
    'Sara',
    'Tigbauan',
    'Tubungan',
    'Zarraga',
  ],
  Isabela: [
    'Alicia',
    'Angadanan',
    'Aurora',
    'Benito Soliven',
    'Burgos',
    'Cabagan',
    'Cabatuan',
    'Cauayan',
    'Cordon',
    'Delfin Albano (Magsaysay)',
    'Dinapigue',
    'Divilacan',
    'Echague',
    'Gamu',
    'Ilagan',
    'Jones',
    'Luna',
    'Maconacon',
    'Mallig',
    'Naguilian',
    'Palanan',
    'Quezon',
    'Quirino',
    'Ramon',
    'Reina Mercedes',
    'Roxas',
    'San Agustin',
    'San Guillermo',
    'San Isidro',
    'San Manuel',
    'San Mariano',
    'San Mateo',
    'San Pablo',
    'Santa Maria',
    'Santiago',
    'Santo Tomas',
    'Tumauini',
  ],
  Kalinga: ['Balbalan', 'Lubuagan', 'Pasil', 'Pinukpuk', 'Rizal', 'Tabuk', 'Tanudan', 'Tinglayan'],
  Laguna: [
    'Alaminos',
    'Bay',
    'Binan',
    'Cabuyao',
    'Calamba',
    'Calauan',
    'Cavinti',
    'Famy',
    'Kalayaan',
    'Liliw',
    'Los Banos',
    'Luisiana',
    'Lumban',
    'Mabitac',
    'Magdalena',
    'Majayjay',
    'Nagcarlan',
    'Paete',
    'Pagsanjan',
    'Pakil',
    'Pangil',
    'Pila',
    'Rizal',
    'San Pablo',
    'San Pedro',
    'Santa Cruz',
    'Santa Maria',
    'Santa Rosa',
    'Siniloan',
    'Victoria',
  ],
  'Lanao Del Norte': [
    'Bacolod',
    'Baloi',
    'Baroy',
    'Iligan',
    'Kapatagan',
    'Kauswagan',
    'Kolambugan',
    'Lala',
    'Linamon',
    'Magsaysay',
    'Maigo',
    'Matungao',
    'Munai',
    'Nunungan',
    'Pantao Ragat',
    'Pantar',
    'Poona Piagapo',
    'Salvador',
    'Sapad',
    'Sultan Naga Dimaporo',
    'Tagoloan',
    'Tangcal',
    'Tubod',
  ],
  'La Union': [
    'Agoo',
    'Aringay',
    'Bacnotan',
    'Bagulin',
    'Balaoan',
    'Bangar',
    'Bauang',
    'Burgos',
    'Caba',
    'Luna',
    'Naguilian',
    'Pugo',
    'Rosario',
    'San Fernando',
    'San Gabriel',
    'San Juan',
    'Santol',
    'Santo Tomas',
    'Sudipen',
    'Tubao',
  ],
  'Lazada Office': ['Laguna', 'Taguig'],
  Leyte: [
    'Abuyog',
    'Alangalang',
    'Albuera',
    'Babatngon',
    'Barugo',
    'Bato',
    'Baybay',
    'Burauen',
    'Capoocan',
    'Carigara',
    'Dagami',
    'Dulag',
    'Hilongos',
    'Hindang',
    'Inopacan',
    'Isabel',
    'Jaro',
    'Javier',
    'Julita',
    'Kananga',
    'La Paz',
    'Leyte',
    'Macarthur',
    'Mahaplag',
    'Matag-Ob',
    'Matalom',
    'Mayorga',
    'Merida',
    'Ormoc',
    'Palo',
    'Palompon',
    'Pastrana',
    'San Isidro',
    'San Miguel',
    'Santa Fe',
    'Tabango',
    'Tabontabon',
    'Tacloban',
    'Tanauan',
    'Tolosa',
    'Tunga',
    'Villaba',
  ],
  Marawi: ['Marawi'],
  Marinduque: ['Boac', 'Buenavista', 'Gasan', 'Mogpog', 'Santa Cruz', 'Torrijos'],
  'Metro Manila': [
    'Caloocan',
    'Las Pinas',
    'Makati',
    'Malabon',
    'Mandaluyong',
    'Tondo I / Ii',
    'Binondo',
    'Ermita',
    'Intramuros',
    'Malate',
    'Manila',
    'Paco',
    'Pandacan',
    'Port Area',
    'Quiapo',
    'Sampaloc',
    'San Miguel',
    'San Nicolas',
    'Santa Ana',
    'Santa Cruz',
    'Santa Mesa',
    'Marikina',
    'Muntinlupa',
    'Navotas',
    'Paranaque',
    'Pasay',
    'Pasig',
    'Pateros',
    'Quezon',
    'San Juan',
    'Taguig',
    'Valenzuela',
  ],
  'Misamis Occidental': [
    'Aloran',
    'Baliangao',
    'Bonifacio',
    'Calamba',
    'Clarin',
    'Concepcion',
    'Don Victoriano Chiongbian',
    'Jimenez',
    'Lopez Jaena',
    'Oroquieta',
    'Ozamiz',
    'Panaon',
    'Plaridel',
    'Sapang Dalaga',
    'Sinacaban',
    'Tangub',
    'Tudela',
  ],
  'Misamis Oriental': [
    'Alubijid',
    'Balingasag',
    'Balingoan',
    'Binuangan',
    'Cagayan De Oro',
    'Claveria',
    'El Salvador',
    'Gingoog',
    'Gitagum',
    'Initao',
    'Jasaan',
    'Kinoguitan',
    'Lagonglong',
    'Laguindingan',
    'Libertad',
    'Lugait',
    'Magsaysay',
    'Manticao',
    'Medina',
    'Naawan',
    'Opol',
    'Salay',
    'Sugbongcogon',
    'Tagoloan',
    'Talisayan',
    'Villanueva',
  ],
  'Mountain Province': [
    'Barlig',
    'Bauko',
    'Besao',
    'Bontoc',
    'Natonin',
    'Paracelis',
    'Sabangan',
    'Sadanga',
    'Sagada',
    'Tadian',
  ],
  'Negros Occidental': [
    'Bacolod',
    'Bago',
    'Binalbagan',
    'Cadiz',
    'Calatrava',
    'Candoni',
    'Cauayan',
    'Enrique B. Magalona',
    'Escalante',
    'Himamaylan',
    'Hinigaran',
    'Hinoba-An',
    'Ilog',
    'Isabela',
    'Kabankalan',
    'La Carlota',
    'La Castellana',
    'Manapla',
    'Moises Padilla',
    'Murcia',
    'Pontevedra',
    'Pulupandan',
    'Sagay',
    'Salvador Benedicto',
    'San Carlos',
    'San Enrique',
    'Silay',
    'Sipalay',
    'Talisay',
    'Toboso',
    'Valladolid',
    'Victorias',
  ],
  'Negros Oriental': [
    'Amlan',
    'Ayungon',
    'Bacong',
    'Bais',
    'Basay',
    'Bayawan',
    'Bindoy',
    'Canlaon',
    'Dauin',
    'Dumaguete',
    'Guihulngan',
    'Jimalalud',
    'La Libertad',
    'Mabinay',
    'Manjuyod',
    'Pamplona',
    'San Jose',
    'Santa Catalina',
    'Siaton',
    'Sibulan',
    'Tanjay',
    'Tayasan',
    'Valencia',
    'Vallehermoso',
    'Zamboanguita',
  ],
  'North Cotabato': [
    'Alamada',
    'Aleosan',
    'Antipas',
    'Arakan',
    'Banisilan',
    'Carmen',
    'Kabacan',
    'Kidapawan',
    'Libungan',
    'Magpet',
    'Makilala',
    'Matalam',
    'Midsayap',
    'Pigkawayan',
    'Pikit',
    'President Roxas',
    'Tulunan',
  ],
  'Northern Samar': [
    'Allen',
    'Biri',
    'Bobon',
    'Capul',
    'Catarman',
    'Catubig',
    'Gamay',
    'Laoang',
    'Lapinig',
    'Las Navas',
    'Lavezares',
    'Lope De Vega',
    'Mapanas',
    'Mondragon',
    'Palapag',
    'Pambujan',
    'Rosario',
    'San Antonio',
    'San Isidro',
    'San Jose',
    'San Roque',
    'San Vicente',
    'Silvino Lobos',
    'Victoria',
  ],
  'Nueva Ecija': [
    'Aliaga',
    'Bongabon',
    'Cabanatuan',
    'Cabiao',
    'Carranglan',
    'Cuyapo',
    'Gabaldon (Bitulok & Sabani)',
    'Gapan',
    'General Mamerto Natividad',
    'General Tinio (Papaya)',
    'Guimba',
    'Jaen',
    'Laur',
    'Licab',
    'Llanera',
    'Lupao',
    'Nampicuan',
    'Palayan',
    'Pantabangan',
    'Penaranda',
    'Quezon',
    'Rizal',
    'San Antonio',
    'San Isidro',
    'San Jose',
    'San Leonardo',
    'Santa Rosa',
    'Santo Domingo',
    'Science Of Munoz',
    'Talavera',
    'Talugtug',
    'Zaragoza',
  ],
  'Nueva Vizcaya': [
    'Alfonso Castaneda',
    'Ambaguio',
    'Aritao',
    'Bagabag',
    'Bambang',
    'Bayombong',
    'Diadi',
    'Dupax Del Norte',
    'Dupax Del Sur',
    'Kasibu',
    'Kayapa',
    'Quezon',
    'Santa Fe',
    'Solano',
    'Villaverde',
  ],
  'Occidental Mindoro': [
    'Abra De Ilog',
    'Calintaan',
    'Looc',
    'Lubang',
    'Magsaysay',
    'Mamburao',
    'Paluan',
    'Rizal',
    'Sablayan',
    'San Jose',
    'Santa Cruz',
  ],
  'Oriental Mindoro': [
    'Baco',
    'Bansud',
    'Bongabong',
    'Bulalacao',
    'Calapan',
    'Gloria',
    'Mansalay',
    'Naujan',
    'Pinamalayan',
    'Pola',
    'Puerto Galera',
    'Roxas',
    'San Teodoro',
    'Socorro',
    'Victoria',
  ],
  Palawan: [
    'Aborlan',
    'Agutaya',
    'Araceli',
    'Balabac',
    'Bataraza',
    'Brooke`s Point',
    'Busuanga',
    'Cagayancillo',
    'Coron',
    'Culion',
    'Cuyo',
    'Dumaran',
    'El Nido (Bacuit)',
    'Linapacan',
    'Magsaysay',
    'Narra',
    'Puerto Princesa',
    'Quezon',
    'Rizal (Marcos)',
    'Roxas',
    'San Vicente',
    'Sofronio Espanola',
    'Taytay',
  ],
  Pampanga: [
    'Angeles',
    'Apalit',
    'Arayat',
    'Bacolor',
    'Candaba',
    'Floridablanca',
    'Guagua',
    'Lubao',
    'Mabalacat',
    'Macabebe',
    'Magalang',
    'Masantol',
    'Mexico',
    'Minalin',
    'Porac',
    'San Fernando',
    'San Luis',
    'San Simon',
    'Santa Ana',
    'Santa Rita',
    'Santo Tomas',
    'Sasmuan',
  ],
  Pangasinan: [
    'Agno',
    'Aguilar',
    'Alaminos',
    'Alcala',
    'Anda',
    'Asingan',
    'Balungao',
    'Bani',
    'Basista',
    'Bautista',
    'Bayambang',
    'Binalonan',
    'Binmaley',
    'Bolinao',
    'Bugallon',
    'Burgos',
    'Calasiao',
    'Dagupan',
    'Dasol',
    'Infanta',
    'Labrador',
    'Laoac',
    'Lingayen',
    'Mabini',
    'Malasiqui',
    'Manaoag',
    'Mangaldan',
    'Mangatarem',
    'Mapandan',
    'Natividad',
    'Pozorrubio',
    'Rosales',
    'San Carlos',
    'San Fabian',
    'San Jacinto',
    'San Manuel',
    'San Nicolas',
    'San Quintin',
    'Santa Barbara',
    'Santa Maria',
    'Santo Tomas',
    'Sison',
    'Sual',
    'Tayug',
    'Umingan',
    'Urbiztondo',
    'Urdaneta',
    'Villasis',
  ],
  Quezon: ['Quezon', 'Lucban'],
  Quirino: ['Aglipay', 'Cabarroguis', 'Diffun', 'Maddela', 'Nagtipunan', 'Saguday'],
  Rizal: [
    'Angono',
    'Antipolo',
    'Baras',
    'Binangonan',
    'Cainta',
    'Cardona',
    'Jala-Jala',
    'Morong',
    'Pililla',
    'Rodriguez (Montalban)',
    'San Mateo',
    'Tanay',
    'Taytay',
    'Teresa',
  ],
  Romblon: [
    'Alcantara',
    'Banton',
    'Cajidiocan',
    'Calatrava',
    'Concepcion',
    'Corcuera',
    'Ferrol',
    'Looc',
    'Magdiwang',
    'Odiongan',
    'Romblon',
    'San Agustin',
    'San Andres',
    'San Fernando',
    'San Jose',
    'Santa Fe',
    'Santa Maria',
  ],
  Sarangani: ['Alabel', 'Glan', 'Kiamba', 'Maasim', 'Maitum', 'Malapatan', 'Malungon'],
  Siquijor: ['Enrique Villanueva', 'Larena', 'Lazi', 'Maria', 'San Juan', 'Siquijor'],
  Sorsogon: [
    'Barcelona',
    'Bulan',
    'Bulusan',
    'Casiguran',
    'Castilla',
    'Donsol',
    'Gubat',
    'Irosin',
    'Juban',
    'Magallanes',
    'Matnog',
    'Pilar',
    'Prieto Diaz',
    'Santa Magdalena',
    'Sorsogon',
  ],
  'South Cotabato': [
    'Banga',
    'General Santos',
    'Koronadal',
    'Lake Sebu',
    'Norala',
    'Polomolok',
    'Santo Nino',
    'Surallah',
    'Tampakan',
    'Tantangan',
    'Tupi',
  ],
  'Southern Leyte': [
    'Anahawan',
    'Bontoc',
    'Hinunangan',
    'Hinundayan',
    'Libagon',
    'Liloan',
    'Limasawa',
    'Maasin',
    'Macrohon',
    'Malitbog',
    'Padre Burgos',
    'Pintuyan',
    'Saint Bernard',
    'San Francisco',
    'San Juan',
    'San Ricardo',
    'Silago',
    'Sogod',
    'Tomas Oppus',
  ],
  'Sultan Kudarat': [
    'Bagumbayan',
    'Columbio',
    'Esperanza',
    'Isulan',
    'Kalamansig',
    'Lambayong',
    'Lebak',
    'Lutayan',
    'Palimbang',
    'President Quirino',
    'Sen. Ninoy Aquino',
    'Tacurong',
  ],
  'Surigao Del Norte': [
    'Alegria',
    'Bacuag',
    'Burgos',
    'Claver',
    'Dapa',
    'Del Carmen',
    'General Luna',
    'Gigaquit',
    'Mainit',
    'Malimono',
    'Pilar',
    'Placer',
    'San Benito',
    'San Francisco',
    'San Isidro',
    'Santa Monica',
    'Sison',
    'Surigao',
    'Tagana-An',
    'Tubod',
  ],
  'Surigao Del Sur': [
    'Barobo',
    'Bayabas',
    'Bislig',
    'Cagwait',
    'Cantilan',
    'Carmen',
    'Carrascal',
    'Cortes',
    'Hinatuan',
    'Lanuza',
    'Lianga',
    'Lingig',
    'Madrid',
    'Marihatag',
    'San Agustin',
    'San Miguel',
    'Tagbina',
    'Tago',
    'Tandag',
  ],
  Tarlac: [
    'Anao',
    'Bamban',
    'Camiling',
    'Capas',
    'Concepcion',
    'Gerona',
    'La Paz',
    'Mayantoc',
    'Moncada',
    'Paniqui',
    'Pura',
    'Ramos',
    'San Clemente',
    'San Jose',
    'San Manuel',
    'Santa Ignacia',
    'Tarlac',
    'Victoria',
  ],
  'Western Samar': [
    'Basey',
    'Calbayog',
    'Calbiga',
    'Catbalogan',
    'Daram',
    'Gandara',
    'Hinabangan',
    'Jiabong',
    'Marabut',
    'Matag-Ob',
    'Matuguinao',
    'Motiong',
    'Pagsanghan',
    'Paranas (Wright)',
    'Pinabacdao',
    'San Jorge',
    'San Jose De Buan',
    'San Sebastian',
    'Santa Margarita',
    'Santa Rita',
    'Santo Nino',
    'Tagapul-An',
    'Talalora',
    'Tarangnan',
    'Villareal',
    'Zumarraga',
  ],
  Zambales: [
    'Botolan',
    'Cabangan',
    'Candelaria',
    'Castillejos',
    'Iba',
    'Masinloc',
    'Olongapo',
    'Palauig',
    'San Antonio',
    'San Felipe',
    'San Marcelino',
    'San Narciso',
    'Santa Cruz',
    'Subic',
  ],
  'Zamboanga Del Norte': [
    'Bacungan (Leon B. Postigo)',
    'Baliguian',
    'Dapitan',
    'Dipolog',
    'Godod',
    'Gutalac',
    'Jose Dalman',
    'Kalawit',
    'Katipunan',
    'Labason',
    'La Libertad',
    'Liloy',
    'Manukan',
    'Mutia',
    'Pinan',
    'Polanco',
    'Pres. Manuel A. Roxas',
    'Rizal',
    'Salug',
    'Sergio Osmena Sr.',
    'Sibuco',
    'Sibutad',
    'Sindangan',
    'Siocon',
    'Sirawai',
    'Tampilisan',
  ],
  'Zamboanga Del Sur': [
    'Aurora',
    'Bayog',
    'Dimataling',
    'Dinas',
    'Dumalinao',
    'Dumingag',
    'Guipos',
    'Josefina',
    'Kumalarang',
    'Labangan',
    'Lakewood',
    'Lapuyan',
    'Mahayag',
    'Margosatubig',
    'Midsalip',
    'Molave',
    'Pagadian',
    'Pitogo',
    'Ramon Magsaysay (Liargo)',
    'San Miguel',
    'San Pablo',
    'Sominot (Don Mariano Marcos)',
    'Tabina',
    'Tambulig',
    'Tigbao',
    'Tukuran',
    'Vincenzo A. Sagun',
    'Zamboanga',
  ],
  'Zamboanga Sibugay': [
    'Alicia',
    'Buug',
    'Diplahan',
    'Imelda',
    'Ipil',
    'Kabasalan',
    'Mabuhay',
    'Malangas',
    'Naga',
    'Olutanga',
    'Payao',
    'Roseller Lim',
    'Siay',
    'Talusan',
    'Titay',
    'Tungawan',
  ],
};
